# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BacklogMcp < Formula
  desc "A local MCP server that gives AI agents read/write access to a story-based project backlog"
  homepage "https://github.com/corbym/backlog-mcp"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/corbym/backlog-mcp/releases/download/v1.1.0/backlog-mcp_1.1.0_darwin_amd64.tar.gz"
      sha256 "5a50e6651bd35260870d70de7811683167832639654400261c411863495b0862"

      define_method(:install) do
        bin.install "backlog-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/corbym/backlog-mcp/releases/download/v1.1.0/backlog-mcp_1.1.0_darwin_arm64.tar.gz"
      sha256 "74daf0fc45db64367444e34daca8cf2bef4f1b69da2f3b69bef2f35f28048f5d"

      define_method(:install) do
        bin.install "backlog-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/corbym/backlog-mcp/releases/download/v1.1.0/backlog-mcp_1.1.0_linux_amd64.tar.gz"
      sha256 "109323fd9910d5c9aed541954c51b0acdf0ef78dd94635b9b8f6b41d13372b0c"
      define_method(:install) do
        bin.install "backlog-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/corbym/backlog-mcp/releases/download/v1.1.0/backlog-mcp_1.1.0_linux_arm64.tar.gz"
      sha256 "138d384db4d03907a9daa75abc75780e2c526d35170998d3388b00ea8dfd0121"
      define_method(:install) do
        bin.install "backlog-mcp"
      end
    end
  end

  test do
    system "#{bin}/backlog-mcp", "--version"
  end
end
