# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BacklogMcp < Formula
  desc "A local MCP server that gives AI agents read/write access to a story-based project backlog"
  homepage "https://github.com/corbym/backlog-mcp"
  version "1.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/corbym/backlog-mcp/releases/download/v1.1.1/backlog-mcp_1.1.1_darwin_amd64.tar.gz"
      sha256 "1466b01b2778ceff458c9180b48249ff3c47902b13cda287b6446224803f5846"

      define_method(:install) do
        bin.install "backlog-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/corbym/backlog-mcp/releases/download/v1.1.1/backlog-mcp_1.1.1_darwin_arm64.tar.gz"
      sha256 "cb39bd1566be687ebae5bcb552b58149c783dfff4bd57ef1169b89a49065c7d9"

      define_method(:install) do
        bin.install "backlog-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/corbym/backlog-mcp/releases/download/v1.1.1/backlog-mcp_1.1.1_linux_amd64.tar.gz"
      sha256 "aee5bbff45e796b39438120e08312d020d99fe76ab5bd52d2c19c6835641fc86"
      define_method(:install) do
        bin.install "backlog-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/corbym/backlog-mcp/releases/download/v1.1.1/backlog-mcp_1.1.1_linux_arm64.tar.gz"
      sha256 "a924e3ca7f5190730cf8b78fbd1f325b851e6074b4b18bb330bd37bb693b141c"
      define_method(:install) do
        bin.install "backlog-mcp"
      end
    end
  end

  test do
    system "#{bin}/backlog-mcp", "--version"
  end
end
